Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7"
  c.vm.hostname = "default-centos-7.vagrantup.com"
  c.vm.network(:forwarded_port, {:guest=>9090, :host=>9090})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/home/simonas/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-sre_hm-default-centos-7-51a5044c-5f05-491c-be17-7311e459f34c"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
